apiVersion: v1
kind: Service
metadata:
  name: my-gpt-flask-app-service
spec:
  type: NodePort
  selector:
    app: my-gpt-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  
